name: lms_admin
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.3
  cached_network_image: ^3.3.1
  chewie: ^1.7.5
  comment_tree: ^0.3.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.0
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  excel: ^4.0.3
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_form_builder: ^9.2.1
  flutter_otp_text_field: ^1.1.1
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  form_builder_validators: ^9.1.0
  get_it: ^7.6.6
  go_router: ^13.0.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.4
  navigation_tool: ^0.1.6
  number_pagination: ^1.0.7
  path: ^1.9.0
  path_provider: ^2.0.11
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  slide_countdown: ^1.5.0
  string_similarity: ^2.0.0
  syncfusion_flutter_pdfviewer: ^24.1.45
  universal_io: ^2.2.2
  url_launcher: ^6.2.4
  video_player: ^2.8.2

dev_dependencies:
  build_runner: ^2.4.8

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    # - assets/images/homeview.png
    - assets/images/
    - assets/translations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
